server:
  port: 8080
  servlet:
    context-path: /poc-mp

spring:
  datasource:
    username: dw-feed
    password: dw_D0c_2022
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.2.1.11:3306/dw

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
app:
  debugMode: true


appConfig:
  runConfig: false
  fetchSize: 1500
  pageSize: 1500
  numberOfLinesToReturnForHealthLog: 10
  useWhereClause: true
  reducerBeginDate: 20190301
  reducerEndDate: 20190731
  sampleDwEventFilePath: /resources/postpayload.json,
  KafkaServers: 10.2.5.5:9092,10.2.5.10:9092,10.2.5.13:9092
  ZookeeperServers: 10.2.5.12:2181,10.2.5.7:2181,10.2.5.11:2181

#this is a wrong guess
#  ZookeeperServers: 10.2.5.5:2181,10.2.5.10:2181,10.2.5.13:2181
#  KafkaServers: 10.2.5.12:9902,10.2.5.7:9902,10.2.5.11:9902

# move the bootstrap server to here
# add the logging configuration


#logging:
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#  level:
#    '[org.springframework.web]': DEBUG
#    '[org.hibernate]': DEBUG
#    '[com.docmatter.resource.server]': DEBUG
#    '[org.springframework.security]': DEBUG
#    '[org.springframework.web.filter.CommonsRequestLoggingFilter]': DEBUG
